"""YouTube Transcript Scraper - Apify Actor entry point."""

from __future__ import annotations

import asyncio
import secrets
from typing import Any

from apify import Actor

from . import yt_client as yt

EVENT_TRANSCRIPT = 'transcript'
EVENT_LISTED = 'video-listed'


class Budget:
    def __init__(self) -> None:
        self.limit_reached = False

    def available(self, event: str, requested: int) -> int:
        """How many events of this type still fit in the run's charge limit (no charge made)."""
        try:
            allowed = Actor.get_charging_manager().calculate_max_event_charge_count_within_limit(event)
        except Exception:  # noqa: BLE001
            allowed = None
        return requested if allowed is None else max(0, min(requested, allowed))

    async def charge(self, event: str, count: int = 1) -> int:
        if count <= 0 or self.limit_reached:
            return 0
        try:
            allowed = Actor.get_charging_manager().calculate_max_event_charge_count_within_limit(event)
        except Exception:  # noqa: BLE001
            allowed = None
        to_charge = count if allowed is None else min(count, allowed)
        if to_charge <= 0:
            self.limit_reached = True
            return 0
        result = await Actor.charge(event, count=to_charge)
        if result.event_charge_limit_reached or to_charge < count:
            self.limit_reached = True
        return to_charge


def _as_list(value: Any) -> list[str]:
    if not value:
        return []
    if isinstance(value, str):
        value = [value]
    return [str(v).strip() for v in value if str(v).strip()]


def _track(t: yt.CaptionTrack | None) -> dict | None:
    if t is None:
        return None
    return {'code': t.language_code, 'name': t.name, 'kind': t.kind, 'isTranslatable': t.is_translatable}


def result_to_item(r: yt.TranscriptResult, *, include_segments: bool, source: dict) -> dict:
    m = r.metadata
    text = r.text or ''
    item = {
        'type': 'transcript',
        'videoId': r.video_id,
        'url': r.url,
        'title': m.title,
        'channel': m.channel,
        'channelId': m.channel_id,
        'durationSeconds': m.duration_seconds,
        'viewCount': m.view_count,
        'likeCount': m.like_count,
        'publishDate': m.publish_date or m.upload_date,
        'description': (m.description or '')[:2000] or None,
        'keywords': m.keywords[:30] if m.keywords else [],
        'thumbnailUrl': m.thumbnail_url,
        'isShort': m.is_short,
        'isLive': m.is_live,
        'language': r.selected_track.language_code if r.selected_track else None,
        'languageName': r.selected_track.name if r.selected_track else None,
        'isAutoGenerated': (r.selected_track.kind == 'auto') if r.selected_track else None,
        'translatedTo': r.translated_to,
        'availableLanguages': [_track(t) for t in r.available_tracks],
        'segmentCount': len(r.segments),
        'wordCount': len(text.split()),
        'text': text,
        **source,
    }
    if include_segments:
        item['segments'] = [{'start': s.start, 'duration': s.duration, 'text': s.text} for s in r.segments]
    return item


async def main() -> None:
    async with Actor:
        inp = await Actor.get_input() or {}
        video_inputs = _as_list(inp.get('videoUrls'))
        channels = _as_list(inp.get('channelUrls'))
        playlists = _as_list(inp.get('playlistUrls'))
        if not video_inputs and not channels and not playlists:
            raise ValueError('Provide at least one of: videoUrls, channelUrls, playlistUrls.')

        languages = _as_list(inp.get('languages')) or ['en']
        prefer_manual = bool(inp.get('preferManual', True))
        fallback_any = bool(inp.get('fallbackToAnyLanguage', True))
        translate_to = (inp.get('translateTo') or '').strip() or None
        include_metadata = bool(inp.get('includeMetadata', True))
        include_segments = bool(inp.get('includeSegments', True))
        channel_source = (inp.get('channelSource') or 'uploads').lower()
        max_per_channel = int(inp.get('maxVideosPerChannel') or 20)
        max_per_playlist = int(inp.get('maxVideosPerPlaylist') or 50)

        proxy_factory = None
        initial_proxy_url = None
        proxy_input = inp.get('proxyConfiguration') or {}
        custom_urls = [str(u).strip() for u in (proxy_input.get('proxyUrls') or []) if str(u).strip()]
        if proxy_input.get('useApifyProxy') or custom_urls:
            proxy_config = await Actor.create_proxy_configuration(actor_proxy_input=proxy_input)
            if proxy_config:
                if custom_urls:
                    # User-supplied (ideally residential) proxies take precedence over Apify
                    # datacenter IPs: build the rotation list up front and cycle it in the
                    # worker thread without awaiting anything.
                    rotation = [await proxy_config.new_url() for _ in custom_urls]
                    initial_proxy_url = rotation[0]
                    cursor = {'i': 0}

                    def _sync_new_url() -> str | None:
                        cursor['i'] = (cursor['i'] + 1) % len(rotation)
                        return rotation[cursor['i']]

                    proxy_factory = _sync_new_url
                    Actor.log.info(f'Using {len(custom_urls)} custom proxy URL(s) from proxyConfiguration.proxyUrls (rotating)')
                else:
                    # Apify Proxy picks a new IP per session id, so a fresh session id == a fresh IP.
                    # Build the URL once (async) and derive new sessions synchronously for worker threads.
                    seed_url = await proxy_config.new_url(session_id='seed0')
                    initial_proxy_url = seed_url

                    def _sync_new_url() -> str | None:
                        if 'session-seed0' in seed_url:
                            return seed_url.replace('session-seed0', f'session-{secrets.token_hex(4)}')
                        return seed_url

                    proxy_factory = _sync_new_url
                    Actor.log.info('Using Apify Proxy (rotating sessions). Note: YouTube may bot-check '
                                   'datacenter IPs on recent videos; residential proxyUrls are recommended for bulk runs.')

        budget = Budget()
        totals = {
            'transcripts': 0, 'listed': 0, 'listedCharged': 0, 'failed': 0,
            'failures': {'botCheck': 0, 'noCaptions': 0, 'unavailable': 0, 'other': 0},
        }

        def _fail(kind: str) -> None:
            totals['failed'] += 1
            totals['failures'][kind] += 1
        client = yt.YouTubeTranscriptClient(
            proxy_url=initial_proxy_url,
            proxy_url_factory=proxy_factory,
            max_retries=3,
            min_delay=0.3,
            logger=lambda m: Actor.log.debug(m),
        )

        # 1. Build the video queue: explicit videos + channel/playlist listings.
        queue: list[tuple[str, dict]] = []
        seen: set[str] = set()

        def add(video: str, source: dict) -> None:
            try:
                vid = yt.extract_video_id(video)
            except Exception:  # noqa: BLE001
                Actor.log.warning(f'Skipping invalid video input: {video}')
                return
            if vid not in seen:
                seen.add(vid)
                queue.append((vid, source))

        for v in video_inputs:
            add(v, {})

        for channel in channels:
            try:
                items = await asyncio.to_thread(client.list_channel_videos, channel, max_per_channel, channel_source)
            except Exception as exc:  # noqa: BLE001
                Actor.log.error(f'Channel {channel}: listing failed ({exc})')
                totals['failed'] += 1
                continue
            items = items[:budget.available(EVENT_LISTED, len(items))]
            Actor.log.info(f'Channel {channel}: {len(items)} videos listed ({channel_source})')
            totals['listed'] += len(items)
            for it in items:
                add(it.video_id, {'sourceChannel': channel, 'listedTitle': getattr(it, 'title', None)})

        for playlist in playlists:
            try:
                items = await asyncio.to_thread(client.list_playlist_videos, playlist, max_per_playlist)
            except Exception as exc:  # noqa: BLE001
                Actor.log.error(f'Playlist {playlist}: listing failed ({exc})')
                totals['failed'] += 1
                continue
            items = items[:budget.available(EVENT_LISTED, len(items))]
            Actor.log.info(f'Playlist {playlist}: {len(items)} videos listed')
            totals['listed'] += len(items)
            for it in items:
                add(it.video_id, {'sourcePlaylist': playlist, 'listedTitle': getattr(it, 'title', None)})

        Actor.log.info(f'{len(queue)} video(s) to transcribe')

        # 2. Transcribe.
        consecutive_blocks = 0
        for index, (video_id, source) in enumerate(queue, start=1):
            if budget.limit_reached:
                Actor.log.warning('Maximum charge limit reached - stopping')
                break
            try:
                result = await asyncio.to_thread(
                    client.get_transcript, video_id,
                    languages, prefer_manual, translate_to, fallback_any, include_metadata,
                )
            except (yt.NoCaptionsAvailable, yt.LanguageNotAvailable, yt.VideoUnavailable, yt.AgeRestricted) as exc:
                Actor.log.warning(f'[{index}/{len(queue)}] {video_id}: {type(exc).__name__}: {exc}')
                await Actor.push_data({'type': 'error', 'videoId': video_id, 'url': f'https://www.youtube.com/watch?v={video_id}',
                                       'error': type(exc).__name__, 'message': str(exc), **source})
                _fail('noCaptions' if isinstance(exc, (yt.NoCaptionsAvailable, yt.LanguageNotAvailable)) else 'unavailable')
                consecutive_blocks = 0
                continue
            except (yt.RateLimited, yt.BotCheckRequired) as exc:
                consecutive_blocks += 1
                Actor.log.warning(f'[{index}/{len(queue)}] {video_id}: {type(exc).__name__}: {exc}')
                await Actor.push_data({'type': 'error', 'videoId': video_id, 'url': f'https://www.youtube.com/watch?v={video_id}',
                                       'error': type(exc).__name__, 'message': str(exc), **source})
                _fail('botCheck')
                if consecutive_blocks >= 5:
                    Actor.log.error('YouTube is blocking this run repeatedly (bot check / rate limit on this IP range) - stopping to avoid wasted requests. '
                                    'Failed videos are not charged. Retry later or pass residential proxy URLs in proxyConfiguration.proxyUrls.')
                    break
                await asyncio.sleep(3 * consecutive_blocks)
                continue
            except Exception as exc:  # noqa: BLE001
                Actor.log.exception(f'[{index}/{len(queue)}] {video_id}: failed ({exc})')
                await Actor.push_data({'type': 'error', 'videoId': video_id, 'url': f'https://www.youtube.com/watch?v={video_id}',
                                       'error': type(exc).__name__, 'message': str(exc)[:300], **source})
                _fail('other')
                continue

            consecutive_blocks = 0
            if not await budget.charge(EVENT_TRANSCRIPT, 1):
                break
            # The listing fee is settled only for videos whose transcript actually succeeded,
            # so bot-checked or caption-less videos from a channel/playlist cost nothing.
            if source.get('sourceChannel') or source.get('sourcePlaylist'):
                totals['listedCharged'] += await budget.charge(EVENT_LISTED, 1)
            item = result_to_item(result, include_segments=include_segments, source=source)
            await Actor.push_data(item)
            totals['transcripts'] += 1
            Actor.log.info(
                f'[{index}/{len(queue)}] {video_id}: "{(item["title"] or "")[:50]}" {item["language"]}'
                f'{" (auto)" if item["isAutoGenerated"] else ""} - {item["segmentCount"]} segments, {item["wordCount"]} words'
            )

        client.close()
        f = totals['failures']
        Actor.log.info(
            f"Done: {totals['transcripts']} transcripts, {totals['listed']} listed ({totals['listedCharged']} charged), "
            f"{totals['failed']} failed (botCheck={f['botCheck']}, noCaptions={f['noCaptions']}, "
            f"unavailable={f['unavailable']}, other={f['other']})"
        )
        await Actor.set_value('SUMMARY', totals)
        if totals['transcripts'] == 0:
            hint = ('YouTube bot-checked every video on this IP range; pass residential proxy URLs in proxyConfiguration.proxyUrls and retry.'
                    if f['botCheck'] else 'Check the video URLs, or retry later if YouTube blocked the run.')
            raise RuntimeError(f'No transcript could be fetched. {hint}')
